import React, { useCallback, useEffect, useMemo, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "@/navigation/types";
import { BuyerGate } from "@/components/BuyerGate"; import { OasisButton } from "@/components/OasisButton"; import { Screen } from "@/components/Screen"; import { ErrorState, LoadingState } from "@/components/StateViews";
import { buyerFulfilmentStage } from "@/lib/order-stages"; import { parseRpcError } from "@/lib/rpc-errors"; import { customerGateway } from "@/services/customerGateway"; import type { CustomerOrderStatus, CustomerStatement } from "@/types/database.types"; import { colors, spacing, typography } from "@/theme";
type Props=NativeStackScreenProps<RootStackParamList,"DeliveredClosure">;
export function DeliveredClosureScreen({navigation,route}:Props){const {orderId}=route.params;const [orders,setOrders]=useState<CustomerOrderStatus[]>([]);const [statement,setStatement]=useState<CustomerStatement|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [statementError,setStatementError]=useState<string|null>(null);
 /** Loads delivery truth independently from optional commercial-closure facts. */
 const load=useCallback(async()=>{setError(null);setStatementError(null);const [o,s]=await Promise.allSettled([customerGateway.orders(),customerGateway.statement()]);if(o.status==="fulfilled")setOrders(o.value??[]);else setError(parseRpcError(o.reason).message);if(s.status==="fulfilled")setStatement(s.value);else{setStatement(null);setStatementError("Commercial closure details are temporarily unavailable.");}setLoading(false);},[]);useEffect(()=>{void load();},[load]);
 const order=useMemo(()=>orders.find(o=>o.order_id===orderId)??null,[orderId,orders]);const entry=useMemo(()=>statement?.entries.find(e=>e.order_id===orderId)??null,[orderId,statement]);
 return <BuyerGate onLogin={()=>navigation.navigate("Login")} onRegister={()=>navigation.navigate("Register")}><Screen title="Order Delivered" subtitle={order?.order_number??""}>{loading?<LoadingState message="Checking your order…"/>:error?<ErrorState message={error} onRetry={load}/>:!order?<ErrorState message="Order not found." onRetry={load}/>:buyerFulfilmentStage(order.customer_stage)!=="delivered"?<ErrorState message="This order has not been marked delivered yet." onRetry={load}/>:<View style={styles.body}><View style={styles.hero}><Text style={styles.eyebrow}>DELIVERED</Text><Text style={styles.title}>We hope everything arrived perfectly.</Text><Text style={styles.copy}>Review your documents, order again, or tell us if anything needs attention.</Text></View>{statementError?<Text style={styles.note}>{statementError}</Text>:null}{entry?.complaint_deadline?<Text style={styles.note}>Report any delivery issue by {new Date(entry.complaint_deadline).toLocaleDateString()}.</Text>:null}{entry?.commercially_closed?<Text style={styles.closed}>This order is commercially complete.</Text>:null}<OasisButton label="Report an issue" onPress={()=>navigation.navigate("MainTabs",{screen:"Support",params:{orderId}})}/><OasisButton label="View documents" variant="secondary" onPress={()=>navigation.navigate("Documents")}/><OasisButton label="Order again" variant="secondary" onPress={()=>navigation.navigate("MainTabs",{screen:"Catalogue"})}/></View>}</Screen></BuyerGate>}
const styles=StyleSheet.create({body:{marginTop:spacing.md,gap:spacing.md},hero:{backgroundColor:colors.surfacePremium,borderRadius:18,padding:spacing.lg,borderWidth:1,borderColor:colors.accentChampagne},eyebrow:{fontFamily:typography.fontFamilySansSemiBold,fontSize:typography.sizeXs,color:colors.success,letterSpacing:1.1},title:{marginTop:spacing.sm,fontFamily:typography.fontFamilySerifBold,fontSize:typography.sizeXl,color:colors.textPrimary},copy:{marginTop:spacing.sm,fontFamily:typography.fontFamilySans,fontSize:typography.sizeSm,color:colors.textSecondary,lineHeight:20},note:{fontFamily:typography.fontFamilySansMedium,fontSize:typography.sizeSm,color:colors.textSecondary},closed:{fontFamily:typography.fontFamilySansSemiBold,fontSize:typography.sizeSm,color:colors.success}});
